# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8461a469df7caa35e48e4c26ddc4ce6991762b8be09dad3b93ff66152d9d36da81d99829901077e37b2ea4174a4ca9d14e957c64a187409c2d67634dfa985bb6

test:
  secret_key_base: 3c667747dfdd67d78e23c279c34421866cb69ad36bee1f992af479abbbc6f04019593d4356ed5871221efd70e76bb584ec395e6be29f7a7184a4de5f5e17f3e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
